{\rtf1\ansi\ansicpg1252\cocoartf1138\cocoasubrtf510
{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
\margl1440\margr1440\vieww16200\viewh12900\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural

\f0\fs36 \cf0 all: bench\
\
bench: bench.o getmem.o freemem.o get_mem_stats.o print_heap.o\
	gcc bench.o getmem.o freemem.o get_mem_stats.o print_heap.o -o bench\
\
bench.o: bench.c\
	gcc -Wall -c bench.c\
\
getmem.o: getmem.c\
	gcc -Wall -c getmem.c\
\
freemem.o: freemem.c\
	gcc -Wall -c freemem.c\
\
get_mem_stats.o: get_mem_stats.c\
	gcc -Wall -c get_mem_stats.c\
\
print_heap.o: print_heap.c\
	gcc -Wall -c print_heap.c\
\
clean:\
	rm -rf *o bench}